### ISSUE TITLE
separate trace from fix in TracedCat

### ISSUE THREAD

**Issue by zliu41** [con-kitty/categorifier#55]
`fix` requires a Cartesian category whereas `trace` can be implemented for weaker categories. Currently, we have them in the same class because we only ever generate `fix` in the plugin. However, a user could use `ArrowLoop.loop` and have it translated directly to `trace`, allowing us to target weaker traced categories.

(Extricated from https://kitty-hawk.atlassian.net/browse/SW-3207)

**Comment by sellout** [comment]
This is done. `TracedCat` is upstream in concat, and `FixedCat` is in https://github.com/con-kitty/categorifier/blob/master/integrations/concat-extensions/category/Categorifier/ConCatExtensions.hs#L182
